[[plugins]]
repo = 'junegunn/goyo.vim'
hook_add = '''
  let g:goyo_width = 80
  let g:goyo_height = '100%'
  nnoremap <silent> <leader>g :Goyo<CR>
  augroup Goyo
    autocmd!
    autocmd User GoyoEnter :nnoremap j gj
    autocmd User GoyoEnter :nnoremap k gk
    autocmd User GoyoLeave :nnoremap j j
    autocmd User GoyoLeave :nnoremap k k
  augroup END
'''
