[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
    imap <expr><Tab> neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<Tab>"
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
