syntax on
set guifont=Hack\ Nerd\ Font:h17
set transparency=5
set lines=999
set columns=9999

set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
set guioptions-=b

