[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = '''
  let g:neocomplete#enable_at_startup = 1
  let g:neocomplete#enable_smart_case = 1
  let g:neocomplete#enable_underbar_completion = 1
  let g:neocomplete#enable_camel_case_completion = 1
  let g:neocomplete#enable_auto_close_preview = 1
'''

# [[plugins]]
# repo = 'SirVer/ultisnips'
# hook_add = '''
#   let g:UltiSnipsExpandTrigger = "<tab>"
#   let g:UltiSnipsJumpForwardTrigger  = "<c-b>"
#   let g:UltiSnipsJumpBackwardTrigger = "<c-z>"
#   let g:UltiSnipsEditSplit = "vertical"
# '''


# [[plugins]]
# repo = 'honza/vim-snippets'
