#!/bin/bash

if pmset > /dev/null 2>&1; then
  battery_info=$(pmset -g ps | awk 'NR==2{print $3 $4}')
elif acpi > /dev/null 2>&1; then
  battery_info=$(acpi -b | awk '{print $4 $3}' | tr ',[:upper:]' ';[:lower:]')
else
  exit 1
fi
remain=${battery_info%%%*}
[ ! ${battery_info#*;} = 'charging;' ]; charging=$?

color=''
if [ $charging -eq 1 ]; then
  color='#[fg=colour36]'
elif [ $remain -le 15 ]; then
  color='#[fg=colour196]'
elif [ $remain -le 30 ]; then
  color='#[fg=colour226]'
fi

echo " #[bg=colour239]$color $remain% #[default]"
