#!/bin/bash

type pmset > /dev/null 2>&1 || exit 1;

battery_info=$(pmset -g ps | awk 'NR==2{print $3 $4}')
remain=${battery_info%%%*}

[ ! ${battery_info#*;} = 'charging;' ]; charging=$?

[ $charging -eq 1 ] && icons=('' '' '' '' '' '' '') || icons=('' '' '' '' '' '' '' '' '' '')

icons_cnt=${#icons[@]}
[ $remain -ge 100 ] && icon=${icons[$((icons_cnt - 1))]} || icon=${icons[$((remain * icons_cnt / 100))]}

icon_color=''
if [ $charging -eq 1 ]; then
  icon_color='#[fg=colour36]'
elif [ $remain -le 15 ]; then
  icon_color='#[fg=colour196]'
elif [ $remain -le 30 ]; then
  icon_color='#[fg=colour226]'
fi

echo " #[bg=colour239 fg=colour255] $remain% $icon_color$icon #[default]"
