#!/bin/bash

TPMDIR=~/repos/github.com/tmux-plugins/tpm
if [ $# -ge 1 ]; then
  TPMDIR=$1
fi

if [ -d $TPMDIR ]; then
  exit 0
fi
git clone 'https://github.com/tmux-plugins/tpm.git' $TPMDIR >/dev/null 2>&1

