PATH=$PATH:/Applications/MacVim.app/Contents/bin
if [ -d ~/bin ]; then
  PATH=$PATH:~/bin
fi
export PATH

export LSCOLORS=ExFxCxdxBxegedabagacad
export LESSHISTFILE=${DOTFILES}/less_history

JavaFXLib=$JavaFXLib:~/Prog/Java/javafx-sdk-11.0.2/lib/
export JavaFXLib
