PATH=$PATH:/Applications/MacVim.app/Contents/bin
if [ -d ~/bin ]; then
  PATH=$PATH:~/bin
fi
export PATH

export LSCOLORS=ExFxCxdxBxegedabagacad
export LESSHISTFILE=${DOTFILES}/less_history


export JAVA_HOME=$(/usr/libexec/java_home)
JavaFXLib=$JavaFXLib:~/Prog/Java/javafx-sdk-11.0.2/lib/
export JavaFXLib

export XDG_CONFIG_HOME=${DOTFILES}
export XDG_DATA_HOME=${XDG_CONFIG_HOME}
