[[plugins]]
repo = 'junegunn/goyo.vim'
hook_add = '''
  let g:goyo_width = 80
  let g:goyo_height = '100%'
  nnoremap <silent> <leader>g :Goyo<CR>
  augroup Goyo
    autocmd!
    autocmd User GoyoEnter :nnoremap j gj
    autocmd User GoyoEnter :nnoremap k gk
    autocmd User GoyoEnter :nnoremap J gJ
    autocmd User GoyoLeave :nnoremap j j
    autocmd User GoyoLeave :nnoremap k k
    autocmd User GoyoLeave :nnoremap J J
  augroup END
'''


[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  let g:ale_enabled = 0
  let g:ale_lint_on_text_changed = 'always'
  let g:ale_linters_explicit = 1  " Only run linters named in ale_linters settings.
  let g:ale_linters = {
    \ 'python': ['pylint'],
    \ 'java':   ['javac']
    \}
  nmap <leader>ak <Plug>(ale_previous_wrap)
  nmap <leader>aj <Plug>(ale_next_wrap)
  nnoremap <silent> <leader>aa :<C-u>ALEToggle<CR>

  if !has('nvim')
    let g:ale_sign_error = ''
    let g:ale_sign_warning = ''
  endif
  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_warning_str = 'W'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

  if isdirectory('src')
    let g:ale_java_javac_classpath = getcwd() . '/src'
  endif

  augroup ALEColor
    autocmd!
    autocmd ColorScheme * highlight ALEErrorSign   ctermfg=203 ctermbg=NONE guibg=NONE
    autocmd ColorScheme * highlight ALEWarningSign ctermfg=216 ctermbg=NONE guibg=NONE
  augroup END
'''
