[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'vim-jp/vimdoc-ja'


[[plugins]]
repo = 'sainnhe/edge'
merged = '0'


[[plugins]]
repo = 'tpope/vim-surround'


[[plugins]]
repo = 'tpope/vim-repeat'


[[plugins]]
repo = 'tpope/vim-commentary'


[[plugins]]
repo = "cespare/vim-toml"


[[plugins]]
repo = "aklt/plantuml-syntax"


[[plugins]]
repo = 'junegunn/fzf'
merged = '0'


[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  let g:fzf_layout = {'down': '50%'}
  let g:fzf_commits_log_options = '--graph --decorate --pretty=oneline --all --abbrev-commit'

  nnoremap <silent> <leader>ff <Cmd>Files<CR>
  nnoremap <silent> <leader>fb <Cmd>Buffers<CR>
  nnoremap <silent> <leader>fr <Cmd>Rg<CR>
  nnoremap <silent> <leader>fg <Cmd>GFiles?<CR>
  nnoremap <silent> <leader>fh <Cmd>Helptags<CR>

  imap <c-x><c-k> <plug>(fzf-complete-word)
  imap <c-x><c-f> <plug>(fzf-complete-path)
  imap <c-x><c-l> <plug>(fzf-complete-line)
'''


[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set laststatus=2
  let s:mode_map = {
    \   'n': 'N',
    \   'i': 'I',
    \   'R': 'R',
    \   'v': 'V',
    \   'V': 'VL',
    \   "\<C-v>": 'VB',
    \   'c': 'C',
    \   's': 'S',
    \   'S': 'SL',
    \   "\<C-s>": 'SB',
    \   't': 'T',
    \}
  let g:lightline = {
    \ 'colorscheme': 'seoul256',
    \ 'active': {
    \   'left':  [['modewithskk'],
    \             ['filename'],
    \            ],
    \   'right': [['filetype'],
    \             ['fileencoding'],
    \             ['aleactive', 'fileformat'],
    \            ]
    \ },
    \ 'inactive': {
    \   'left':  [['filename']],
    \   'right': []
    \ },
    \ 'mode_map': s:mode_map,
    \ 'component_function': {
    \   'aleactive': 'LLAleActive',
    \   'modewithskk': 'ModeWithSkk'
    \ },
    \ }

  function! ModeWithSkk() abort
    let l:mode = mode()
    let l:mode_str = get(s:mode_map, l:mode, l:mode)
    if !(exists('g:loaded_skkeleton') && dein#is_sourced('skkeleton') && skkeleton#is_enabled())
      return l:mode_str
    end
    let l:skk_mode = skkeleton#mode()
    let l:eskk_mode_str = get({'hira': 'あ', 'kata': 'ア'}, l:skk_mode, l:skk_mode)
    return l:mode_str . '-' . l:eskk_mode_str
  endfunction

  function! LLAleActive() abort
    if !dein#is_sourced('ale')
      return ''
    endif
    if !g:ale_enabled
      return 'disabled'
    endif
    if len(ale#linter#Get(&filetype)) == 0
      return 'no linter'
    endif

    let l:counts = ale#statusline#Count(bufnr(''))
    let l:num_errors = l:counts.error + l:counts.style_error
    let l:num_warnings = l:counts.total - l:num_errors
    return printf('E%dW%d', l:num_errors, l:num_warnings)
  endfunction
'''
