" options
set guifont=Hack\ Nerd\ Font:h17
set guioptions=
set lines=999
set columns=9999
let s:transparency = 15
let &transparency = 0

" mapping
command GVIMTransparencyToggle let &transparency = s:transparency - &transparency
nnoremap <silent> <D-u> :<C-u>GVIMTransparencyToggle<CR>

if !exists("g:loaded_tmux_navigator")
  nnoremap <C-h> <C-w>h
  nnoremap <C-j> <C-w>j
  nnoremap <C-k> <C-w>k
  nnoremap <C-l> <C-w>l
endif
syntax enable
