" options
set guifont=Hack\ Nerd\ Font:h17
let s:transparency = 15
let &transparency = s:transparency
set lines=999
set columns=9999

set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
set guioptions-=b

" color
set runtimepath+=~/repos/dein.vim/repos/github.com/cocopon/iceberg.vim
colorscheme iceberg

" mapping
command TransparencyToggle let &transparency = s:transparency - &transparency
nnoremap <silent> <D-u> :<C-u>TransparencyToggle<CR>

if !exists("g:loaded_tmux_navigator")
  nnoremap <C-h> <C-w>h
  nnoremap <C-j> <C-w>j
  nnoremap <C-k> <C-w>k
  nnoremap <C-l> <C-w>l
endif
