" options
set guifont=Hack\ Nerd\ Font:h17
set transparency=15
set lines=999
set columns=9999

set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
set guioptions-=b

" color
set runtimepath+=~/repos/dein.vim/repos/github.com/cocopon/iceberg.vim
colorscheme iceberg

" mapping
nnoremap <silent> <D-u> :<C-u>let &transparency = 15 - &transparency<CR>
if !exists("g:loaded_tmux_navigator")
  nnoremap <C-h> <C-w>h
  nnoremap <C-j> <C-w>j
  nnoremap <C-k> <C-w>k
  nnoremap <C-l> <C-w>l
endif
