scriptencoding utf-8
set encoding=utf-8

if &compatible
  set nocompatible
endif

let g:VIM_ROOT = $DOTFILES . '/vim'
let g:NVIM_ROOT = $DOTFILES . '/nvim'
if has('nvim')
  let g:ROOT_DIR = g:NVIM_ROOT
else
  let g:ROOT_DIR = g:VIM_ROOT
endif

let g:mapleader = "\<Space>"


function! s:source_file(filename)
  if !filereadable(a:filename)
    echo 'File Not Found : ' . a:filename
    return
  endif
  execute 'source' . a:filename
endfunction

function! HomeToTilde(path)
  let l:escaped_home = escape(expand('~'), '/')
  return substitute(a:path, '^' . l:escaped_home, '~', '')
endfunction

" options
call s:source_file(g:VIM_ROOT . '/optionrc.vim')

" neovim
if has('nvim')
  call s:source_file(g:NVIM_ROOT . '/neovimrc.vim')
endif

" dein
" FIXME: Snippets are not loaded after opening vim.
"        I think the cache of dein does some evil deeds.
if has('nvim')
  call s:source_file(g:VIM_ROOT . '/deinrc.vim')
endif

" color
call s:source_file(g:VIM_ROOT . '/colorrc.vim')
" syntax enable

" mapping
call s:source_file(g:VIM_ROOT . '/mappingrc.vim')
