scriptencoding utf-8
set encoding=utf-8

if &compatible
  set nocompatible
endif

let g:VIM_ROOT  = $DOTFILES . '/vim'
let g:NVIM_ROOT = $DOTFILES . '/nvim'
if has('nvim')
  let g:ROOT_DIR = g:NVIM_ROOT
else
  let g:ROOT_DIR = g:VIM_ROOT
endif

let g:mapleader = "\<Space>"

function! _error(msg)
  echohl WarningMsg | echomsg '[dotfiles] ' . a:msg | echohl None
endfunction

function! s:source_file(filename)
  if !filereadable(a:filename)
    call _error(printf('file %s is not found.', a:filename))
    return
  endif
  execute 'source' . a:filename
endfunction

function! HomeToTilde(path)
  let l:escaped_home = escape(expand('~'), '/')
  return substitute(a:path, '^' . l:escaped_home, '~', '')
endfunction

function! IsAvailableTrueColor()
  return $COLORTERM == 'truecolor' || $COLORTERM == '24bit'
endfunction

" options
call s:source_file(g:VIM_ROOT . '/optionrc.vim')

" neovim
if has('nvim')
  call s:source_file(g:NVIM_ROOT . '/neovimrc.vim')
endif

" dein
call s:source_file(g:VIM_ROOT . '/deinrc.vim')

" color
call s:source_file(g:VIM_ROOT . '/colorrc.vim')

" mapping
call s:source_file(g:VIM_ROOT . '/mappingrc.vim')

" local vimrc
if filereadable('.vimrc.local')
  call s:source_file('.vimrc.local')
endif

" default plugins
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1
